site_name: Sitio de Joaquín para IAW

nav:
  - Principal: index.md
  - Acerca de: create_site.md
  - Primera documentación: first.md
  - Segunda documentación: second.md

theme: 
  name: material
  palette:
    primary: cyan
    accent: orange
  font:
    text: Montserrat
    code: Montserrat
  logo: logo/logo.jpg
  lenguaje: es